const Creds = {
  VITE_SUPABASE_URL:'https://brzcsujwqcoaicqvbndd.supabase.co',
  VITE_SUPABASE_ANON_KEY:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyemNzdWp3cWNvYWljcXZibmRkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTY4NzQ3NCwiZXhwIjoyMDY3MjYzNDc0fQ.A4-IqeaX09E5J03Udsv3xJW7D2C1f7lrexFe_dlzhBA'
}

export default Creds;
